In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/home/prince/Data science/01_Practice/Pandas/00/hotel_bookings.csv')

In [4]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [5]:
df.rename(columns = {'adults': 'num_adults', 'childrens':'num_childrens', 'babies' : 'num_babies'}, inplace=True)

In [6]:
df['agent'].fillna(-1, inplace=True)

/tmp/ipykernel_4646/3845202393.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['agent'].fillna(-1, inplace=True)

In [7]:
df.isnull().sum() * 100/len(df)

hotel                              0.000000
is_canceled                        0.000000
lead_time                          0.000000
arrival_date_year                  0.000000
arrival_date_month                 0.000000
arrival_date_week_number           0.000000
arrival_date_day_of_month          0.000000
stays_in_weekend_nights            0.000000
stays_in_week_nights               0.000000
num_adults                         0.000000
children                           0.003350
num_babies                         0.000000
meal                               0.000000
country                            0.408744
market_segment                     0.000000
distribution_channel               0.000000
is_repeated_guest                  0.000000
previous_cancellations             0.000000
previous_bookings_not_canceled     0.000000
reserved_room_type                 0.000000
assigned_room_type                 0.000000
booking_changes                    0.000000
deposit_type                       0.000000
agent                              0.000000
company                           94.306893
days_in_waiting_list               0.000000
customer_type                      0.000000
adr                                0.000000
required_car_parking_spaces        0.000000
total_of_special_requests          0.000000
reservation_status                 0.000000
reservation_status_date            0.000000
dtype: float64

In [8]:
df[df['children'].isna()]
df.dropna(subset=['children'], inplace=True)

In [9]:
df.drop(columns=['company'], inplace=True)

In [10]:
df['country'].fillna('unknown', inplace=True)

/tmp/ipykernel_4646/51666288.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['country'].fillna('unknown', inplace=True)

In [11]:
df.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
num_adults                          int64
children                          float64
num_babies                          int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
dtype: object

In [12]:
df = df.astype({'children':'int', 'is_repeated_guest':'boolean', 'is_canceled':'boolean', 'agent': 'int'})
df.dtypes

hotel                              object
is_canceled                       boolean
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
num_adults                          int64
children                            int64
num_babies                          int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                 boolean
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                               int64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
dtype: object

In [25]:
labels = ['0-100', '101-200','201-300','301-400','401-500','501-600','601-700','701-800']
bins = [0,100, 200, 300, 400, 500, 600, 700, 800]
df['lead_time_bins']= pd.cut(df['lead_time'], labels=labels, bins=bins)
df[['lead_time','lead_time_bins']]
df.drop(columns='lead_time')
df.rename(columns= {'lead_time_bins': 'lead_time'}, inplace=True)

In [15]:
df['arrival_date'] = (
    df['arrival_date_year'].astype(str) + '-' +
    df['arrival_date_month'].astype(str) + '-' +
    df['arrival_date_day_of_month'].astype(str)
)

In [ ]:
df = df.drop(['arrival_date_year', 'arrival_date_month', 'arrival_date_day_of_month'], axis=1)
df[['arrival_date']]

          arrival_date
0          2015-July-1
1          2015-July-1
2          2015-July-1
3          2015-July-1
4          2015-July-1
...                ...
119385  2017-August-30
119386  2017-August-31
119387  2017-August-31
119388  2017-August-31
119389  2017-August-29

[119386 rows x 1 columns]

In [24]:
df.loc[df.duplicated(keep=False)]
df.drop_duplicates(keep='first', inplace=True)

In [26]:
#Completed
df.head(20)

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,num_adults,children,num_babies,meal,...,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,lead_time,arrival_date
0,Resort Hotel,False,342,27,0,0,2,0,0,BB,...,-1,0,Transient,0.00,0,0,Check-Out,2015-07-01,301-400,2015-July-1
1,Resort Hotel,False,737,27,0,0,2,0,0,BB,...,-1,0,Transient,0.00,0,0,Check-Out,2015-07-01,701-800,2015-July-1
2,Resort Hotel,False,7,27,0,1,1,0,0,BB,...,-1,0,Transient,75.00,0,0,Check-Out,2015-07-02,0-100,2015-July-1
3,Resort Hotel,False,13,27,0,1,1,0,0,BB,...,304,0,Transient,75.00,0,0,Check-Out,2015-07-02,0-100,2015-July-1
4,Resort Hotel,False,14,27,0,2,2,0,0,BB,...,240,0,Transient,98.00,0,1,Check-Out,2015-07-03,0-100,2015-July-1
6,Resort Hotel,False,0,27,0,2,2,0,0,BB,...,-1,0,Transient,107.00,0,0,Check-Out,2015-07-03,NaN,2015-July-1
7,Resort Hotel,False,9,27,0,2,2,0,0,FB,...,303,0,Transient,103.00,0,1,Check-Out,2015-07-03,0-100,2015-July-1
8,Resort Hotel,True,85,27,0,3,2,0,0,BB,...,240,0,Transient,82.00,0,1,Canceled,2015-05-06,0-100,2015-July-1
9,Resort Hotel,True,75,27,0,3,2,0,0,HB,...,15,0,Transient,105.50,0,0,Canceled,2015-04-22,0-100,2015-July-1
10,Resort Hotel,True,23,27,0,4,2,0,0,BB,...,240,0,Transient,123.00,0,0,Canceled,2015-06-23,0-100,2015-July-1
11,Resort Hotel,False,35,27,0,4,2,0,0,HB,...,240,0,Transient,145.00,0,0,Check-Out,2015-07-05,0-100,2015-July-1
12,Resort Hotel,False,68,27,0,4,2,0,0,BB,...,240,0,Transient,97.00,0,3,Check-Out,2015-07-05,0-100,2015-July-1
13,Resort Hotel,False,18,27,0,4,2,1,0,HB,...,241,0,Transient,154.77,0,1,Check-Out,2015-07-05,0-100,2015-July-1
14,Resort Hotel,False,37,27,0,4,2,0,0,BB,...,241,0,Transient,94.71,0,0,Check-Out,2015-07-05,0-100,2015-July-1
15,Resort Hotel,False,68,27,0,4,2,0,0,BB,...,240,0,Transient,97.00,0,3,Check-Out,2015-07-05,0-100,2015-July-1
16,Resort Hotel,False,37,27,0,4,2,0,0,BB,...,8,0,Contract,97.50,0,0,Check-Out,2015-07-05,0-100,2015-July-1
17,Resort Hotel,False,12,27,0,1,2,0,0,BB,...,240,0,Transient,88.20,0,0,Check-Out,2015-07-02,0-100,2015-July-1
18,Resort Hotel,False,0,27,0,1,2,0,0,BB,...,-1,0,Transient,107.42,0,0,Check-Out,2015-07-02,NaN,2015-July-1
19,Resort Hotel,False,7,27,0,4,2,0,0,BB,...,250,0,Transient,153.00,0,1,Check-Out,2015-07-05,0-100,2015-July-1
20,Resort Hotel,False,37,27,1,4,1,0,0,BB,...,241,0,Transient,97.29,0,1,Check-Out,2015-07-06,0-100,2015-July-1